package de.garden.sensors;

import static de.garden.sensors.WetterInformation.*;

import java.util.Objects;
import java.util.Random;

/**
 * Reading data form sensor SoilMoisture<br><br>
 * 
 * SoilMonsure is the sensor that can read temperature,<br> 
 * sunlight in lux and soil moisture<br><br>
 * 
 * @author grzeg
 *
 */
public class SoilMoisture {
	
//	*******************************************
//	*				  Attributs
//	*******************************************

	/**
	 * Actual temperature in Celcius
	 */
	protected double temperature;
	
	/**
	 * Actual sunlight value, useful to check night or day<br>
	 * Possible valuess from 0 to 100
	 */
	protected int lux;
	
	/**
	 * Actual soil moisture<br>
	 * Possible values between 0-100
	 */
	protected int moisture;

//	*******************************************
//	*				Konstruktors
//	*******************************************
	
	/**
	 * In this class constructor all values are autogenerated.<br>
	 * We can use it in fake read symulation.
	 */
	public SoilMoisture() {
		Random lotto= new Random();
		double rest = lotto.nextDouble();
		// short output to 2 places after 0,01
		rest *= 100;
		rest = Math.round(rest);
		rest /= 100;
		this.temperature = lotto.nextInt(20) + 10 + rest;
		this.lux = lotto.nextInt(100);
		this.moisture = lotto.nextInt(100);
	}
	
	/**
	 * Standard constructor.<br>
	 * In this class construktor we can add values manual <br>
	 * @param temperature is ntemperature
	 * @param lux is sunlight
	 * @param moisture is soil moisture
	 */
	public SoilMoisture(double temperature, int lux, int moisture) {
		this.temperature = temperature;
		this.lux = lux;
		this.moisture = moisture;
	}
	
//	*******************************************
//	*				 Functions
//	*******************************************
	
	/**
	 * Here we use sunlight 'lux' parametr to know how<br> 
	 * cloudy is sky right now<br><br>
	 * 
	 * We have 4 strings outputs possibilitys<br>
	 * '0 - 24'   no sunlight, night<br>
	 * '25 - 49'  cloudy sky, no sunlight, maybe rain come<br>
	 * '50 - 74'  partly clouds and sun<br>
	 * '75 - 100' fullsunlight, day, no clouds<br><br>
	 * 
	 * @return how cloudy is right now
	 */
	public String wetterLux() {
		if (lux < 24) {
			return DARK.getText();
		}
		else if (lux >=25 & lux < 50) {
			return CLOUD.getText();
		}
		else if (lux >=50 & lux < 75) {
			return PARTCLOUD.getText();
		}
		else {
			return SUN.getText();
		}
	}
	
	/**
	 * Here we use 'moinsture' parametr to know how<br> 
	 * soil moinsture is in erde<br><br>
	 * 
	 * We have 2 strings outputs possibilitys<br>
	 * '0 - 49'  Erde is dry<br>
	 * '50 - 100' Erde is wet<br><br>
	 * 
	 * @return how dry erde is right now
	 */
	public String wetterErd() {
		if (moisture < 50) {
			return DRY.getText();
		}
		else {
			return WET.getText();
		}
	}
	
	/**
	 * Here we use 'temperature' parametr to know<br> 
	 * how will plants grows<br><br>
	 * 
	 * We have 3 strings outputs possibilitys<br>
	 * '0 - 16'  It is to cold<br>
	 * '17 - 21'  It is optimal<br>
	 * '22 - and higer' It is comfortable<br><br>
	 * 
	 * @return actual string wether
	 */
	public String wetterTemp() {
		if (temperature < 17) {
			return COLD.getText();
		}
		else if (temperature >=17 & temperature < 22) {
			return SUN.getText();
		}
		else {
			return HOT.getText();
		}
	}
	
	/**
	 * Getter for temperature
	 * @return the temperature
	 */
	public double getTemperature() {
		return temperature;
	}

	/**
	 * Setter for temperature
	 * @param temperature is the temperature to set
	 */
	public void setTemperature(double temperature) {
		this.temperature = temperature;
	}

	/**
	 * Getter for sunlights
	 * @return the lux
	 */
	public int getLux() {
		return lux;
	}

	/**
	 * Setter for sunlights
	 * @param lux is the lux to set
	 */
	public void setLux(int lux) {
		this.lux = lux;
	}

	/**
	 * @return the moinsure
	 */
	public int getMoisture() {
		return moisture;
	}

	/**
	 * Setter for soil moisture
	 * @param moisture is the moinsure to set
	 */
	public void setMoisture(int moisture) {
		this.moisture = moisture;
	}

	@Override
	public int hashCode() {
		return Objects.hash(lux, moisture, temperature);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SoilMoisture other = (SoilMoisture) obj;
		return lux == other.lux && moisture == other.moisture
				&& Double.doubleToLongBits(temperature) == Double.doubleToLongBits(other.temperature);
	}
	
	@Override
	public String toString() {
		return "SoilMoisture [temperature=" + temperature + ", lux=" + lux + ", moisture=" + moisture + "]";
	}
	
}
